### ISSUE TITLE
create/use a frontmatter template

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-templater#1]
I tried to create a template but it seems it doesn't import the data as long as it is between the 3 dashes. Any chance to circumvent it, and copy a frontmatter set (property set)?

**Comment by plylrnsdy** [comment]
fixed in v1.0.2

**Comment by thob** [comment]
Hmm, 
it works if there's no frontmatter properties! But if there already is,the frontmatter properties are copied outside the yaml block see
![2024-11-11_08-41](https://github.com/user-attachments/assets/018fc903-fb8e-4bc4-99d3-87395faa50cf)
Any chance to replace an existing block or insert it with the 
\---
frontmatter properties: 
\--- 
_of course I could delete the default frontmatter properties, so it's empty for each new document_

**Comment by plylrnsdy** [comment]
fixed in 1.0.3
